/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg:           'rgb(var(--color-bg) / <alpha-value>)',
        card:         'rgb(var(--color-card) / <alpha-value>)',
        'card-hover': 'rgb(var(--color-card-hover) / <alpha-value>)',
        border:       'rgb(var(--color-border) / <alpha-value>)',
        'border-subtle': 'rgb(var(--color-border-subtle) / <alpha-value>)',
        accent:       'rgb(var(--color-accent) / <alpha-value>)',
        violet:       'rgb(var(--color-violet) / <alpha-value>)',
        blue:         'rgb(var(--color-blue) / <alpha-value>)',
        amber:        'rgb(var(--color-amber) / <alpha-value>)',
        red:          'rgb(var(--color-red) / <alpha-value>)',
        'text-primary': 'rgb(var(--color-text-primary) / <alpha-value>)',
        'text-muted':   'rgb(var(--color-text-muted) / <alpha-value>)',
        'text-subtle':  'rgb(var(--color-text-subtle) / <alpha-value>)',
      },
      fontFamily: {
        heading: ['Syne', 'sans-serif'],
        mono:    ['"DM Mono"', 'monospace'],
        body:    ['Inter', 'sans-serif'],
      },
      animation: {
        'fade-in':      'fadeIn 0.2s ease-out',
        'fade-up':      'fadeUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-up':     'slideUp 0.35s cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-in':     'scaleIn 0.2s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'check-pop':    'checkPop 0.22s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'pulse-soft':   'pulseSoft 2.5s ease-in-out infinite',
        'pulse-ring':   'pulseRing 2s ease-out infinite',
        'shimmer':      'shimmer 2s linear infinite',
        'float':        'float 6s ease-in-out infinite',
        'glow-pulse':   'glowPulse 2s ease-in-out infinite',
        'slide-in-bottom': 'slideInBottom 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'count-up':     'countUp 0.4s ease-out',
        'bounce-in':    'bounceIn 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        fadeIn:   { from: { opacity: '0' }, to: { opacity: '1' } },
        fadeUp:   { from: { opacity: '0', transform: 'translateY(10px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideUp:  { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:  { from: { opacity: '0', transform: 'scale(0.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        checkPop: { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.28)' }, '100%': { transform: 'scale(1)' } },
        pulseSoft:{ '0%,100%': { opacity: '1' }, '50%': { opacity: '0.35' } },
        pulseRing:{ '0%': { transform: 'scale(1)', opacity: '0.8' }, '100%': { transform: 'scale(1.6)', opacity: '0' } },
        shimmer:  { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        float:    { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-8px)' } },
        glowPulse:{ '0%,100%': { boxShadow: '0 0 8px rgba(139,92,246,0.3)' }, '50%': { boxShadow: '0 0 24px rgba(139,92,246,0.6)' } },
        slideInBottom: { from: { opacity: '0', transform: 'translateY(24px) scale(0.96)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        countUp:  { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        bounceIn: { '0%': { transform: 'scale(0.6)', opacity: '0' }, '60%': { transform: 'scale(1.1)' }, '100%': { transform: 'scale(1)', opacity: '1' } },
      },
      boxShadow: {
        'glow-accent': '0 0 20px rgba(139,92,246,0.25), 0 0 60px rgba(139,92,246,0.1)',
        'glow-green':  '0 0 20px rgba(16,185,129,0.25), 0 0 60px rgba(16,185,129,0.08)',
        'glow-amber':  '0 0 20px rgba(245,158,11,0.25)',
        'glow-sm':     '0 0 10px rgba(139,92,246,0.2)',
        'card':        '0 1px 3px rgba(0,0,0,0.4), 0 8px 32px rgba(0,0,0,0.3)',
        'card-hover':  '0 2px 8px rgba(0,0,0,0.5), 0 16px 48px rgba(0,0,0,0.35)',
        'elevated':    '0 4px 16px rgba(0,0,0,0.5), 0 24px 64px rgba(0,0,0,0.4)',
      },
      backdropBlur: {
        xs: '4px',
      },
    },
  },
  plugins: [],
};
